version: '3.1'

services:

  database:
    image: postgres:15
    container_name: hello_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_HELLO_PASSWORD}
      POSTGRES_USER: ${DB_HELLO_USER}
      POSTGRES_DB: ${DB_HELLO_NAME}
    ports: 
      - ${DB_HELLO_PORT}:5432